git:
  lfs_skip_smudge: true

matrix:
  include:
    - os: linux
      dist: xenial
      env: 
        - APP_NAME="FBX2glTF-linux-x64"
        - CONAN_CONFIG="-s compiler.libcxx=libstdc++11"
    - os: osx
      osx_image: xcode10.2
      env:
        - APP_NAME="FBX2glTF-darwin-x64"
        - CONAN_CONFIG="-s compiler=apple-clang -s compiler.version=10.0 -s compiler.libcxx=libc++"
compiler: gcc
language: generic
cache:
  directories:
  - ${HOME}/.conan

addons:
  apt:
    packages: zstd
  homebrew:
    packages: zstd

install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- conda config --set always_yes yes
- conda info -a
- conda create -n travis_env python=3.7 pip
- conda activate travis_env
- pip install conan
- conan user
- conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
- conan install . -i build -s build_type=Release ${CONAN_CONFIG}
- conan build . -bf build
- mv build/FBX2glTF build/${APP_NAME}

notifications:
  webhooks:
    - "https://code.facebook.com/travis/webhook/"
deploy:
  provider: releases
  api_key:
    secure: V9CTmZKM7yvsT/WCesJ/tLTuapSf0oIp73zyZrwID7zQtXaq1QJSna4tWM2T0qeZIYhniH1/mqEr2jZVW1txmYn9ZxUMH1Nmp9zzOGl/q+JlRrJUi6HRUWWhCMz003L90whngyOcGI+T7rHtcVcby4owVsze15SrQqqV74NXI8DYNIbNgQR1Nwmqsrg0QirFPEBaIKDAiKonnRDWKPy2P8vqnN9fLhj00uHLwuvahlKAnWFEbNnFbiRScKifB+Mlo6Pf6r64iikrxS2jBxAgSsvPLkuemWLmaHTeGbJMM82aqh5vGSvgYcExvZi+0RdXeIcBdv/jaivM/xge4aZ+4P+IJoX32ZNCcYFMsqES+a6TztkywMs2k1r5gV6LrTjeXJsINSW+BDFdmrwmkudETc4gelQgkMmEkdCwFHENtZGl65z8HJDQKcu9F8NQlhNU7Z5rwQNLmYccvktSDhwbFSG5eq2kFFfcbVx3ovvn1voRTNnyhhVD2ZnLepSQInAVkZbaLkE90bQ+t9icf8uDdHDn17zOQaAZuecPlSW1y4XUCJnZCi0JPLhdSmQYiF60LHYI6xDneC8pmIz8kCUbk921zu8bJBy7zKHmfHy2vqNlPKuRULRIs5QzY31jf2PVZHzB5zX3KSqx9Dd+3DtgbLX2HLaZnANbkQc0rr1X2kk=
  file: build/${APP_NAME}
  skip_cleanup: true
  on:
    repo: facebookincubator/FBX2glTF
    tags: true
